jobs:
  build:
    docker:
      - image: apache:latest
    steps:
      - checkout
      - run : echo "this is build job"
  build_deploy:
    machine:
      image:  ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: install aws cli
          command: |
            sudo apt-get update
            sudo apt-get install aws-cli -y
      - run: ls -la
      
workflows:
  version: 2
  execute_bulk:
    jobs:
      - build       
