jobs:
  build_deploy:
    machine:
      image:  ubuntu:latest
    steps:
      - checkout
      - run:
          name: install aws cli
          command: |
            sudo apt-get update
            sudo apt-get install aws-cli -y
      - run: ls -la
          
