format_version: 10
pipelines:
  pipeline5-script:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      pipeline5:
        git: https://github.com/praveen6370/circleci_test.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - stage5-script:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job5-script:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
            - exec:
                arguments:
                - --version
                command: docker
                run_if: passed
            - exec:
                arguments:
                - 
                command: aws sts get-caller-identity
                         aws s3 ls
                run_if: passed
            - exec:
                arguments:
                - -v
                command: terraform
                run_if: passed
    parameters:
      para: '555'
