jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run : echo "this is build job"
  build_deploy:
    docker:
      image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: install aws cli jq
          command: |
            sudo apt-get update
            sudo apt-get -y update; apt-get -y install git curl jq python3-pip
            sudo pip3 install -U awscli
            sudo curl -fsSL https://get.docker.com -o get-docker.sh
            sudo curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
            sudo tfswitch 0.12.23
      - run:  echo "===================719018074674========frontend==================="
      - run:  terraform init --backend-config="access_key=$AWS_ACCESS_KEY_ID" --backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
      - run:  aws sts assume-role --role-arn "arn:aws:iam::719018074674:role/sil_jenkins" --role-session-name "jenkins-connect" >    assume-role-output.txt
              export AWS_ACCESS_KEY_ID=`cat assume-role-output.txt | jq -c '.Credentials.AccessKeyId' | tr -d '"' | tr -d ' '`
              export AWS_SECRET_ACCESS_KEY=`cat assume-role-output.txt | jq -c '.Credentials.SecretAccessKey' | tr -d '"' | tr -d ' '`
              export AWS_SESSION_TOKEN=`cat assume-role-output.txt | jq -c '.Credentials.SessionToken' | tr -d '"' | tr -d ' '`
              rm -f assume-role-output.txt
              aws sts get-caller-identity
              
      
workflows:
  version: 2
  execute_bulk:
    jobs:
      - build
      - build_deploy
