version: 2.1
orbs:
  win: circleci/windows@2.2.0
  
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: install aws cli jq
          shell: powershell.exe
          command: |
            docker info
            docker run hello-world:nanoserver-1809
      - run:  git clone git@gitlab.z5x.tech:z5x-tech/Weyyak/weyyak-dotnet-new.git 
             
