jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run : echo "this is build job"
  build_deploy:
    machine:
      image:  ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: install aws cli jq
          command: |
            sudo apt-get update
            echo $PRAVEEN
#            sudo apt-get install aws-cli -y
      - run: ls -l
      
workflows:
  version: 2
  execute_bulk:
    jobs:
      - build
      - build_deploy
